# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a58a58e9005b48d9de1b131d65aa73bb0bebccbf36b4c3d289edb121e918c6becfaa0e6f9c15f8de056f8a04d96427082ba9c832b1b8b7778932d78a014ca700

test:
  secret_key_base: 8dc88ab27335e905bc93981470b744a22029f6071e68b98c01d23ab3b686c06d52e38005ead58369c0222783191539712856291f1ac2b9b150ccee29f966f246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
